services:
  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./app.py:/app/app.py
      - ./src:/app/src
      - ./tests:/app/tests
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: mb4-curator-api-dev
    networks:
      - shared_network

networks:
  shared_network:
    external: true
